# Generated by Django 5.0.7 on 2024-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gbl_restaurant_no", models.IntegerField()),
                ("restaurant_name", models.CharField(max_length=255)),
                ("restaurant_address", models.TextField()),
                ("restaurant_owner_id", models.IntegerField()),
                ("restaurant_open_date", models.DateField()),
                ("restaurant_close_date", models.DateField(blank=True, null=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
